./embed.exe --var-name=header_template tools/templates/fixed_hash_map_header.txt > tools/templates/fixed_hash_map_header.h
./embed.exe --var-name=source_template tools/templates/fixed_hash_map_source.txt > tools/templates/fixed_hash_map_source.h
clang -DJSL_DEBUG -fno-omit-frame-pointer -fno-optimize-sibling-calls -O0 -glldb -std=c11 -Wall -Wextra -Wconversion -Wsign-conversion -Wshadow -Wconditional-uninitialized -Wcomma -Widiomatic-parentheses -Wpointer-arith -Wassign-enum -Wswitch-enum -Wimplicit-fallthrough -Wnull-dereference -Wmissing-prototypes -Wundef -pedantic -o tests/bin/generate_hash_map.exe -Isrc/ tools/generate_hash_map.c

./tests/bin/generate_hash_map.exe --name FixedIntToIntMap --function-prefix fixed_int32_to_int32_map --key-type int32_t --value-type int32_t --fixed --header --add-header ../tests/hash_maps/fixed_int32_to_int32_map.h --add-header ../tests/test_hash_map_types.h > tests/hash_maps/fixed_int32_to_int32_map.h
./tests/bin/generate_hash_map.exe --name FixedIntToIntMap --function-prefix fixed_int32_to_int32_map --key-type int32_t --value-type int32_t --fixed --source --add-header ../tests/hash_maps/fixed_int32_to_int32_map.h --add-header ../tests/test_hash_map_types.h > tests/hash_maps/fixed_int32_to_int32_map.c

./tests/bin/generate_hash_map.exe --name FixedCompositeType3ToCompositeType2Map --function-prefix fixed_comp3_to_comp2_map --key-type CompositeType3 --value-type CompositeType2 --fixed --header --add-header ../tests/hash_maps/fixed_comp3_to_comp2_map.h --add-header ../tests/test_hash_map_types.h > tests/hash_maps/fixed_comp3_to_comp2_map.h
./tests/bin/generate_hash_map.exe --name FixedCompositeType3ToCompositeType2Map --function-prefix fixed_comp3_to_comp2_map --key-type CompositeType3 --value-type CompositeType2 --fixed --source --add-header ../tests/hash_maps/fixed_comp3_to_comp2_map.h --add-header ../tests/test_hash_map_types.h > tests/hash_maps/fixed_comp3_to_comp2_map.c
